### ISSUE TITLE
升级固件

### ISSUE THREAD

**Issue by ghost** [KevinMX/openwrt-phicomm-k2p-build#1]
升级固件方面的问题我已经Google处理，有个新的问题，请问怎么编译32m+512m的固件，是编译好的固件自适应的吗

**Comment by Leisuredpootle** [comment]
还有两个问题想请教一下，怎样编译32+512的固件，是编译好的固件会自动检测吗？如果要添加usb3和2支持，我是否还需要做什么吗？麻烦您帮我解答一下，谢谢！

**Comment by Leisuredpootle** [comment]
不好意思，我已经通过baidu和Google获得了解答，不好意思，打扰了.

**Comment by KevinMX** [comment]
直接编译出来的应该不是自适应，我的k2p没有硬改故无法进行测试。
不知道你是否已经解决，以下是我找到的：
https://right.com.cn/FORUM/forum.php?mod=viewthread&tid=342241

**Comment by ghost** [comment]
官方源已经有了相关commit，不过还是谢谢您
