### ISSUE TITLE
编译固件死机问题

### ISSUE THREAD

**Issue by kizimirua** [KevinMX/openwrt-phicomm-k2p-build#10]
您好，我想问一个关于K2P编译软轿包的问题，我自己编译出来个固件老死机，用别人的就没有，然后也翻了很多教程都没看到说又要特别注意的软件包，请问您能告知一下是缺了哪些基础软件吗？谢谢

**Comment by KevinMX** [comment]
把你的.config贴上来看看？

**Comment by kizimirua** [comment]
[config.txt](https://github.com/KevinMX/openwrt-phicomm-k2p-build/files/4406675/config.txt)

**Comment by KevinMX** [comment]
建议移除.config之后重新配置一下。有些配置已经不是最新的了。死机的问题我基本没有遇到过，可以检查一下固件有没有超容/吃满存储空间。
（默认的配置编译出来应该是不会死机的。）

**Comment by protocold** [comment]
I have the same problem. I have K2P rev A1. In fact, I just tried your R20.3.19-2 and it kill my box as well: https://github.com/KevinMX/openwrt-phicomm-k2p-build/releases/download/R20.3.19-2/openwrt-ramips-mt7621-phicomm_k2p-squashfs-sysupgrade.bin

**Comment by KevinMX** [comment]
> I have the same problem. I have K2P rev A1. In fact, I just tried your R20.3.19-2 and it kill my box as well: https://github.com/KevinMX/openwrt-phicomm-k2p-build/releases/download/R20.3.19-2/openwrt-ramips-mt7621-phicomm_k2p-squashfs-sysupgrade.bin

I'm using Padavan recently (mainly for better wireless support), so I won't be able to test it for now. If you are willing to test, I can compile a new one.

**Comment by KevinMX** [comment]
另外，我打算切换到 @MeIsReallyBa 的[lede](https://github.com/MeIsReallyBa/lede) 作为上游源码，因为似乎他revert了之前lean已经revert的hwnat patch，我不清楚Lean为什么revert了这个patch，但是这个patch似乎是起作用的。

BTW, I'm planning to switch to @MeIsReallyBa 's [lede](Mehttps://github.com/MeIsReallyBa/lede) as upstream code repository. Seems that he reverted the patch for mt7621 hwnat which was reverted by lean/coolsnowwolf. I have no idea why coolsnowwolf reverted the hwnat patch, but it seems that it did work.

**Comment by protocold** [comment]
yes I can test. It is rather easy for me to revert. Did you compile padavan yourself too? The reason why I didnt use padavan is because I had problem adding additional packages on it, and it seems like it require external usb storage for such. Is there a way to get around it?

**Comment by KevinMX** [comment]
> yes I can test. It is rather easy for me to revert. Did you compile padavan yourself too? The reason why I didnt use padavan is because I had problem adding additional packages on it, and it seems like it require external usb storage for such. Is there a way to get around it?

Nope, I'm using https://opt.cn2qq.com/padavan/K2P_DRV_V5_3.4.3.9-099.trx for now. For my experiences these days, Padavan will auto detect if you have USB external storage, if not, it will download plugins into RAM, which, for most circumstances, is not a big problem. Of course if you are using applications which requires a huge amount of RAM, you will run into issues though. For example clash is not very stable on my K2P/A2. But for wireless connection speeds, at least in my case, it does out performs lean's openwrt, ~130Mbps+ DL in 2.4GHz, for Lean's openwrt it can only goes ~40Mbps in 2.4GHz.

**Comment by protocold** [comment]
oh whoa.. i am looking to improve wifi as well, mine was acting up recently so I changed the 3 capacitors and it did improve, however i shall try padavan.

what I want to add from the packages was zerotier.

**Comment by KevinMX** [comment]
> oh whoa.. i am looking to improve wifi as well, mine was acting up recently so I changed the 3 capacitors and it did improve, however i shall try padavan.
> 
> what I want to add from the packages was zerotier.

The firmware I'm using doesn't have Zerotier, but it does have ngrok&frp. Maybe you can use them as replacements :)

**Comment by protocold** [comment]
I still dont know why my compilation of lean is so erratic. This isnt the first time for me to compile openwrt. 

If I first select K2P and compile I would get a binary of less than 10MB (pretty much just accept all default and I only add zerotier). If I compile again, it will generate a bin of around 15MB size. 

Maybe I am smoking something.

**Comment by protocold** [comment]
I flashed padavan, and I found out it is using a different section from the flash chip to store the config and is not overwriting openwrt config, because my previous padavan config was still around somehow.

**Comment by MeIsReallyBa** [comment]
我最近在测双7615机器的MT76，里面K2P的.conifg已经不适合K2P了。你说的lean之前加的hwnat 是指github.com/openwrt/openwrt/pull/2815？我没加，看回复说不稳定。不过我加了官方op最近添加的github.com/openwrt/openwrt/commit/6786dc26a205da55ec2d9771693cdfb99e756e59 现在有线的hwnat是正常的，最近在尝试看看能不能搞出无线的hwnat。

**Comment by KevinMX** [comment]
> 我最近在测双7615机器的MT76，里面K2P的.conifg已经不适合K2P了。你说的lean之前加的hwnat 是指github.com/[openwrt/openwrt/pull/2815](https://github.com/openwrt/openwrt/pull/2815)？我没加，看回复说不稳定。不过我加了官方op最近添加的github.com/openwrt/openwrt/commit/6786dc26a205da55ec2d9771693cdfb99e756e59 现在有线的hwnat是正常的，最近在尝试看看能不能搞出无线的hwnat。

我是之前看到Lean Revert了这个[patch](https://github.com/coolsnowwolf/lede/commit/667d594da4a06e83bb5c362ec201213fc126714a)，看来我们说的不是同一个……
不过，之前确实有看到openwrt论坛上有人反馈19.07开始hwnat就不太正常了。期待你的成果。

**Comment by KevinMX** [comment]
> I flashed padavan, and I found out it is using a different section from the flash chip to store the config and is not overwriting openwrt config, because my previous padavan config was still around somehow.

Could you please try this firmware:

[openwrt-ramips-mt7621-phicomm_k2p-squashfs-sysupgrade.bin.zip](https://github.com/KevinMX/openwrt-phicomm-k2p-build/files/4468413/openwrt-ramips-mt7621-phicomm_k2p-squashfs-sysupgrade.bin.zip)

**Comment by protocold** [comment]
This doesnt work. K2P is dead after flashing this.
Also, I found out that padavan that you linked has very slow nat throughput when testing on the lan port. On my 1000M link i can only get 500M download. But when I flash pandorabox 2019.02 version I can get wire speed at 9xxM download.
I will probably stick with this pandorabox version for a few days and see what happen.


    On Monday, April 13, 2020, 03:12:28 PM GMT+8, KevinMX <notifications@github.com> wrote:  
 
 



I flashed padavan, and I found out it is using a different section from the flash chip to store the config and is not overwriting openwrt config, because my previous padavan config was still around somehow.


Could you please try this firmware:

openwrt-ramips-mt7621-phicomm_k2p-squashfs-sysupgrade.bin.zip

**Comment by KevinMX** [comment]
已重新编译并上传release。
测试了一下，2.4GHz 无线性能稍有改善，有线HWNAT正常工作，无线HWNAT无效。等修。
另外Lean新加入的红米AC2100支持会导致我这边编译失败，编译的时候revert了。

Just rebuild it and uploaded to release.
During my test, wireless/2.4GHz performance is slightly improved, HWNAT is working on wired connections,but not working on wireless connections.
BTW, the newly added Redmi AC2100 support caused build errors for me, I've reverted it during build.

**Comment by KevinMX** [comment]
目前的R20.4.8固件经测试已能正常使用。
如仍有问题，请reopen issue。
