### ISSUE TITLE
wifi die intermittently @R20.5.9

### ISSUE THREAD

**Issue by protocold** [KevinMX/openwrt-phicomm-k2p-build#11]
Hi, I used your latest build R20.5.9 and the wifi would die intermittently at random times. 

Do you have any similar issue? 

I am reverting to R20.4.8 and will see if it has the same issue.

**Comment by Zer0xPoint** [comment]
same

**Comment by KevinMX** [comment]
Hi, does reverting to R20.4.8 fix this issue?
Since I'm using [Padavan](https://github.com/chongshengB/rt-n56u) and I'm pretty busy these days, I won't be able to test for now. You can try to report this issue to upstream (coolsnowwolf/lede). I'm just one of the guys who did the compilation work:)

**Comment by protocold** [comment]
seems like it did the trick. But still keeping fingers crossed.

You actually find Padavan better? I find the wifi performance much slower! Do share your finding!

**Comment by KevinMX** [comment]
@protocold Padavan's offloading for WiFi works, and the HWNAT is basically functional, while in OpenWrt/lede's WiFi data traffic is being handled by the CPU (for now) and that lead to very high cpu usage, which can cause some problems. Well, just use the one that works :)

**Comment by KevinMX** [comment]
Will do a rebuild when [#4725](https://github.com/coolsnowwolf/lede/pull/4725/) is merged.

**Comment by KevinMX** [comment]
> Will do a rebuild when [#4725](https://github.com/coolsnowwolf/lede/pull/4725/) is merged.

Already merged. A new build is underway.See: https://github.com/KevinMX/Actions-OpenWrt-Phicomm-K2P
This repo is going to be archived soon. Closing issue for now. If there's still something wrong, I suggest you directly create one in coolsnowwolf/lede.
