### ISSUE TITLE
Lean的源码没集成MTK无线驱动吗？

### ISSUE THREAD

**Issue by myfirebird** [KevinMX/openwrt-phicomm-k2p-build#4]
请问，Lean的源码没集成MTK无线驱动吗？

**Comment by KevinMX** [comment]
~~Lean的源码使用的是**开源驱动** 。~~
似乎已经集成闭源驱动，请自行确认是否可用。
https://github.com/coolsnowwolf/lede/tree/master/package/lean/mt/drivers/mt_wifi

**Comment by myfirebird** [comment]
好的，感谢解答！
