### ISSUE TITLE
最新版本中缺少squashfs-sysupgrade.bin

### ISSUE THREAD

**Issue by witallwang** [KevinMX/openwrt-phicomm-k2p-build#5]
是因为文件改动都在kernel里吗？添加了trojan不应该用户程序也改了么，那就应该需要squashfs的改动啊。

**Comment by KevinMX** [comment]
~~因为是重新构建的，所以只编译出了一个initramfs。使用时需从breed/opboot中刷入（会清空数据）。
另外，似乎~~ 添加了trojan后固件剩余的空间不是很充足，这边暂时无法测试，如出现问题请及时反馈。

**Comment by witallwang** [comment]
谢谢！我今天也重新编译了一遍，确实只有一个initramfs的bin生成。我觉得这应该是个regression。我去upstream提issue试试。

**Comment by KevinMX** [comment]
https://github.com/coolsnowwolf/lede/issues/2381
https://github.com/coolsnowwolf/lede/issues/1797
原因有了，可能是固件过大。我精简一部分插件看看。

**Comment by KevinMX** [comment]
已解决。
取消勾选Luci中ShadowsocksR Plus+的Kcptun之后没有取消勾选Network中的kcptun-client导致固件超容，已重新编译并发releases。之前的版本马上撤下。
