### ISSUE TITLE
老哥搞下passwall呀

### ISSUE THREAD

**Issue by vitoshen** [KevinMX/openwrt-phicomm-k2p-build#7]
据说比ssrplus+更快，老哥有空可以研究研究

**Comment by KevinMX** [comment]
本仓库的上游为[coolsnowwolf/lede](https://github.com/coolsnowwolf/lede/)，目前暂不考虑添加其他仓库中的插件。如有需要自行添加即可。本仓库的config和固件仅供参考。
~~另外，您说的passwall是[Lienol](https://github.com/Lienol/openwrt-package/tree/master/lienol/luci-app-passwall)的这个吗？~~
