### ISSUE TITLE
网络-无线中 2.4G 与 5G 好像显示反了

### ISSUE THREAD

**Issue by aliensvx** [KevinMX/openwrt-phicomm-k2p-build#9]
Interface: rax0 应该是 5G 的。停用按钮也是反的。
![Snipaste_2020-03-04_14-27-55](https://user-images.githubusercontent.com/7090204/75851334-5ec4a280-5e24-11ea-8899-6ea1f90951d2.png)

**Comment by KevinMX** [comment]
k2p的rax0是2.4G，ra0是5G，没问题。不清楚你说的反了是什么情况，应该不影响使用吧？

**Comment by aliensvx** [comment]
按你说的，点击rax0的停用按钮，结果是扫描不到5G信号了。
确实不影响使用，昨天刚刷这个固件发现连2.4G接入点的设备DHCP不到ip，重启下好了，才发现这个问题。
